var countryAbbreviations = {
    "afghanistan": {"code": "AF", "found": false},
    "albania": {"code": "AL", "found": false},
    "algeria": {"code": "DZ", "found": false},
    "andorra": {"code": "AD", "found": false},
    "angola": {"code": "AO", "found": false},
    "antigua and barbuda": {"code": "AG", "found": false},
    "argentina": {"code": "AR", "found": false},
    "armenia": {"code": "AM", "found": false},
    "australia": {"code": "AU", "found": false},
    "austria": {"code": "AT", "found": false},
    "azerbaijan": {"code": "AZ", "found": false},
    "bahamas": {"code": "BS", "found": false},
    "bahrain": {"code": "BH", "found": false},
    "bangladesh": {"code": "BD", "found": false},
    "barbados": {"code": "BB", "found": false},
    "belarus": {"code": "BY", "found": false},
    "belgium": {"code": "BE", "found": false},
    "belize": {"code": "BZ", "found": false},
    "benin": {"code": "BJ", "found": false},
    "bhutan": {"code": "BT", "found": false},
    "bolivia": {"code": "BO", "found": false},
    "bosnia and herzegovina": {"code": "BA", "found": false},
    "botswana": {"code": "BW", "found": false},
    "brazil": {"code": "BR", "found": false},
    "brunei": {"code": "BN", "found": false},
    "bulgaria": {"code": "BG", "found": false},
    "burkina faso": {"code": "BF", "found": false},
    "burundi": {"code": "BI", "found": false},
    "cabo verde": {"code": "CV", "found": false},
    "cambodia": {"code": "KH", "found": false},
    "cameroon": {"code": "CM", "found": false},
    "canada": {"code": "CA", "found": false},
    "central african republic": {"code": "CF", "found": false},
    "chad": {"code": "TD", "found": false},
    "chile": {"code": "CL", "found": false},
    "china": {"code": "CN", "found": false},
    "colombia": {"code": "CO", "found": false},
    "comoros": {"code": "KM", "found": false},
    "democratic republic of the congo": {"code": "CD", "found": false},
    "republic of the congo": {"code": "CG", "found": false},
    "costa rica": {"code": "CR", "found": false},
    "croatia": {"code": "HR", "found": false},
    "cuba": {"code": "CU", "found": false},
    "cyprus": {"code": "CY", "found": false},
    "czech republic": {"code": "CZ", "found": false},
    "denmark": {"code": "DK", "found": false},
    "djibouti": {"code": "DJ", "found": false},
    "dominica": {"code": "DM", "found": false},
    "dominican republic": {"code": "DO", "found": false},
    "ecuador": {"code": "EC", "found": false},
    "egypt": {"code": "EG", "found": false},
    "el salvador": {"code": "SV", "found": false},
    "equatorial guinea": {"code": "GQ", "found": false},
    "eritrea": {"code": "ER", "found": false},
    "estonia": {"code": "EE", "found": false},
    "eswatini": {"code": "SZ", "found": false},
    "ethiopia": {"code": "ET", "found": false},
    "fiji": {"code": "FJ", "found": false},
        "finland": {"code": "FI", "found": false},
    "france": {"code": "FR", "found": false},
    "gabon": {"code": "GA", "found": false},
    "gambia": {"code": "GM", "found": false},
    "georgia": {"code": "GE", "found": false},
    "germany": {"code": "DE", "found": false},
    "ghana": {"code": "GH", "found": false},
    "greece": {"code": "GR", "found": false},
    "grenada": {"code": "GD", "found": false},
    "guatemala": {"code": "GT", "found": false},
    "guinea": {"code": "GN", "found": false},
    "guinea-bissau": {"code": "GW", "found": false},
    "guyana": {"code": "GY", "found": false},
    "haiti": {"code": "HT", "found": false},
    "honduras": {"code": "HN", "found": false},
    "hungary": {"code": "HU", "found": false},
    "iceland": {"code": "IS", "found": false},
    "india": {"code": "IN", "found": false},
    "indonesia": {"code": "ID", "found": false},
    "iran": {"code": "IR", "found": false},
    "iraq": {"code": "IQ", "found": false},
    "ireland": {"code": "IE", "found": false},
    "israel": {"code": "IL", "found": false},
    "italy": {"code": "IT", "found": false},
    "jamaica": {"code": "JM", "found": false},
    "japan": {"code": "JP", "found": false},
    "jordan": {"code": "JO", "found": false},
    "kazakhstan": {"code": "KZ", "found": false},
    "kenya": {"code": "KE", "found": false},
    "kiribati": {"code": "KI", "found": false},
    "north korea": {"code": "KP", "found": false},
    "south korea": {"code": "KR", "found": false},
    "kuwait": {"code": "KW", "found": false},
    "kyrgyzstan": {"code": "KG", "found": false},
    "laos": {"code": "LA", "found": false},
    "latvia": {"code": "LV", "found": false},
    "lebanon": {"code": "LB", "found": false},
    "lesotho": {"code": "LS", "found": false},
    "liberia": {"code": "LR", "found": false},
    "libya": {"code": "LY", "found": false},
    "liechtenstein": {"code": "LI", "found": false},
    "lithuania": {"code": "LT", "found": false},
    "luxembourg": {"code": "LU", "found": false},
    "madagascar": {"code": "MG", "found": false},
    "malawi": {"code": "MW", "found": false},
    "malaysia": {"code": "MY", "found": false},
    "maldives": {"code": "MV", "found": false},
    "mali": {"code": "ML", "found": false},
    "malta": {"code": "MT", "found": false},
    "marshall islands": {"code": "MH", "found": false},
    "mauritania": {"code": "MR", "found": false},
    "mauritius": {"code": "MU", "found": false},
    "mexico": {"code": "MX", "found": false},
    "micronesia": {"code": "FM", "found": false},
    "moldova": {"code": "MD", "found": false},
    "monaco": {"code": "MC", "found": false},
    "mongolia": {"code": "MN", "found": false},
    "montenegro": {"code": "ME", "found": false},
    "morocco": {"code": "MA", "found": false},
    "mozambique": {"code": "MZ", "found": false},
    "myanmar": {"code": "MM", "found": false},
        "namibia": {"code": "NA", "found": false},
    "nauru": {"code": "NR", "found": false},
    "nepal": {"code": "NP", "found": false},
    "netherlands": {"code": "NL", "found": false},
    "new zealand": {"code": "NZ", "found": false},
    "nicaragua": {"code": "NI", "found": false},
    "niger": {"code": "NE", "found": false},
    "nigeria": {"code": "NG", "found": false},
    "north macedonia": {"code": "MK", "found": false},
    "norway": {"code": "NO", "found": false},
    "oman": {"code": "OM", "found": false},
    "pakistan": {"code": "PK", "found": false},
    "palau": {"code": "PW", "found": false},
    "palestine, state of": {"code": "PS", "found": false},
    "panama": {"code": "PA", "found": false},
    "papua new guinea": {"code": "PG", "found": false},
    "paraguay": {"code": "PY", "found": false},
    "peru": {"code": "PE", "found": false},
    "philippines": {"code": "PH", "found": false},
    "poland": {"code": "PL", "found": false},
    "portugal": {"code": "PT", "found": false},
    "qatar": {"code": "QA", "found": false},
    "romania": {"code": "RO", "found": false},
    "russia": {"code": "RU", "found": false},
    "rwanda": {"code": "RW", "found": false},
    "saint kitts and nevis": {"code": "KN", "found": false},
    "saint lucia": {"code": "LC", "found": false},
    "saint vincent and the grenadines": {"code": "VC", "found": false},
    "samoa": {"code": "WS", "found": false},
    "san marino": {"code": "SM", "found": false},
    "sao tome and principe": {"code": "ST", "found": false},
    "saudi arabia": {"code": "SA", "found": false},
    "senegal": {"code": "SN", "found": false},
    "serbia": {"code": "RS", "found": false},
    "seychelles": {"code": "SC", "found": false},
    "sierra leone": {"code": "SL", "found": false},
    "singapore": {"code": "SG", "found": false},
    "slovakia": {"code": "SK", "found": false},
    "slovenia": {"code": "SI", "found": false},
    "solomon islands": {"code": "SB", "found": false},
    "somalia": {"code": "SO", "found": false},
    "south africa": {"code": "ZA", "found": false},
    "south sudan": {"code": "SS", "found": false},
    "spain": {"code": "ES", "found": false},
    "sri lanka": {"code": "LK", "found": false},
    "sudan": {"code": "SD", "found": false},
    "suriname": {"code": "SR", "found": false},
    "sweden": {"code": "SE", "found": false},
    "switzerland": {"code": "CH", "found": false},
    "syria": {"code": "SY", "found": false},
    "taiwan": {"code": "TW", "found": false},
    "tajikistan": {"code": "TJ", "found": false},
    "tanzania": {"code": "TZ", "found": false},
    "thailand": {"code": "TH", "found": false},
    "timor-leste": {"code": "TL", "found": false},
    "togo": {"code": "TG", "found": false},
    "tonga": {"code": "TO", "found": false},
    "trinidad and tobago": {"code": "TT", "found": false},
    "tunisia": {"code": "TN", "found": false},
    "turkey": {"code": "TR", "found": false},
    "turkmenistan": {"code": "TM", "found": false},
    "tuvalu": {"code": "TV", "found": false},
    "uganda": {"code": "UG", "found": false},
    "ukraine": {"code": "UA", "found": false},
    "united arab emirates": {"code": "AE", "found": false},
    "united kingdom": {"code": "GB", "found": false},
    "united states": {"code": "US", "found": false},
    "uruguay": {"code": "UY", "found": false},
    "uzbekistan": {"code": "UZ", "found": false},
    "vanuatu": {"code": "VU", "found": false},
    "vatican city": {"code": "VA", "found": false},
    "venezuela": {"code": "VE", "found": false},
    "vietnam": {"code": "VN", "found": false},
    "yemen": {"code": "YE", "found": false},
    "zambia": {"code": "ZM", "found": false},
    "zimbabwe": {"code": "ZW", "found": false}
};


